#!/bin/bash
#
# Copyright © 2019 Oracle Corp., Inc.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl
#

export PATH=/usr/sbin:/usr/bin:/sbin:/bin

config_dir=/etc/al-config
# AL config
config_file=$config_dir/al.conf
# OCI config: topic OCID etc.
oci_config_file=$config_dir/oci.conf
# OCI SDK/CLI config
oci_cli_config_file=$config_dir/oci_cli.conf
# OCI API private key
oci_api_key_file=$config_dir/oci_api_key.pem
# Yum-cron config
yum_cron_config_file=$config_dir/yum-cron.conf
# cron job
al_cron_job_file=/etc/cron.d/al-update
# log
log_file=/var/log/al.log
# state
al_state_file=/var/lib/al-config/state
al_update_file=/var/lib/al-config/update
system_uuid_file=/var/lib/al-config/system-uuid

# runtime work dir
work_dir=/var/run/al-config

# set default umask
umask 0026

# make sure runtime work dir is created
mkdir -p "$work_dir"

get_time() {
    date "+%F %T,%3N"
}

log() {
    log_info "$*"
}

log_info() {
    echo "$*"
    echo "$(get_time) - ${0##*/}[INFO]: $*" >> "$log_file"
}

log_debug() {
    echo "$(get_time) - ${0##*/}[DEBUG]: $*" >> "$log_file"
}

log_error() {
    echo "$*" >&2
    echo "$(get_time) - ${0##*/}[ERROR]: $*" >> "$log_file"
}

source_config_file() {
    if [ ! -f "$config_file" ]; then
        echo "$config_file doesn't exist." >&2
        exit 1
    fi
    . "$config_file"
}

run_as_root_check() {
    if [ "$(id -u)" != 0 ]; then
        echo "Please run as root." >&2
        exit 1
    fi
}

acquire_lock() {
    local lock_file=/var/run/${0##*/}.lock
    if ! exec 8>"$lock_file"; then
        log_error "Could not create lock file $lock_file."
        exit 1
    fi
    if ! flock -n 8; then
        log_info "Another $0 instance is holding $lock_file, existing"
        exit 1
    fi
}

release_lock() {
    flock -u 8
}

read_file() {
    local f="$1"
    if [[ $f =~ ^(https?|ftp|file):// ]]; then
        curl -sfm 25 "$f" 2>/dev/null
    else
        if [ -r "$f" ]; then
            cat "$f"
        fi
    fi
}

get_instance_name() {
    curl -sfm 25 http://169.254.169.254/opc/v1/instance/displayName 2>/dev/null
}

is_known_exploit_detection_activated() {
    local activated
    if [ -e /proc/sys/kernel/known_exploit_detection ]; then
        activated=$(cat /proc/sys/kernel/known_exploit_detection)
        [ "$activated" = 1 ] && return 0
    fi
    return 1
}

enable_known_exploit_detection() {
    if [ -f /etc/uptrack/uptrack.conf ]; then
        if ! grep -q 'Known-Exploit-Detection' /etc/uptrack/uptrack.conf; then
            cat >> /etc/uptrack/uptrack.conf <<EOF

[Known-Exploit-Detection]
# Known Exploit Detection is another way Ksplice secures your system.
# Ksplice continues to close down vulnerabilities with zero downtime.
# And now you have the added security of being notified when attempted
# privilege escalation attacks are taken on your system.
enabled = yes
EOF
        fi
    fi
}

activate_known_exploit_detection() {
    enable_known_exploit_detection
    command -v ksplice &>/dev/null && ksplice -y kernel upgrade &>/dev/null
}

update_ksplice_access_key() {
    if [ -r /usr/lib/al-config/ksplice_access_key ] && \
        [ -f /etc/uptrack/uptrack.conf ]; then
        local key
        key=$(< /usr/lib/al-config/ksplice_access_key)
        if [ -n "$key" ]; then
            if ! grep -q "^accesskey[[:space:]]*=[[:space:]]*$key$" \
                /etc/uptrack/uptrack.conf; then
                sed -i "s/^accesskey[[:space:]]*=.*/accesskey = $key/g" \
                    /etc/uptrack/uptrack.conf
            fi
        fi
    fi
}

update_system_uuid() {
    local uuid
    uuid=$(dmidecode -s system-uuid 2>/dev/null)
    echo "$uuid" > "$system_uuid_file"
    log_debug "Updated system uuid $uuid"
}

system_uuid_changed() {
    [ -f "$system_uuid_file" ] || update_system_uuid
    local uuid new_uuid
    uuid=$(< "$system_uuid_file")
    new_uuid=$(dmidecode -s system-uuid 2>/dev/null)
    [ "$uuid" != "$new_uuid" ]
}
